class ExistsException(Exception):
    pass

class BadValue(Exception):
    pass